version: '3'

services:

  web:
    image: nginx
    container_name: nginx_container
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/media

  php:
    image: php:7.4-fpm
    container_name: php_container
    networks:
      - backend
    volumes:
      - ./media:/media
  
  python:
    build: .
    container_name: upload_vuln
    volumes:
      - ./media:/app/media
    networks:
      - backend

networks:
  backend:
    external: true



